version: "3.8"

services:
  web:
    build: .
    container_name: inventrack_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env        # reutilizamos tus variables (DB_HOST, DB_USER, etc.)
    depends_on:
      - db
    restart: always
    networks:
      - inventrack_net

  db:
    image: postgres:16
    container_name: inventrack_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - inventrack_db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - inventrack_net

  proxy:
    image: nginx:alpine
    container_name: inventrack_proxy
    depends_on:
      - web
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: always
    networks:
      - inventrack_net

networks:
  inventrack_net:
    driver: bridge

volumes:
  inventrack_db_data:
